---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: unifi
  namespace: unifi
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unifi
  updatePolicy:
    updateMode: Initial
