---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configMapGenerator:
  - name: loki-values
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - loki.values.yaml

resources:
  - loki.helmrelease.yaml
