---
replicas: 2
serviceMonitor:
  enabled: true
config:
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 7d
  ruler:
    alertmanager_url: http://prometheus-kube-prometheus-alertmanager:9093
persistence:
  enabled: true
  size: 15Gi
  storageClassName: longhorn
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: loki.home.frickel.earth
      paths: [/]
  tls:
    - secretName: wildcard.home.frickel.earth-prod
      hosts:
        - loki.home.frickel.earth
