---
serviceMonitor:
  enabled: true

loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

test:
  enabled: false
