---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix

resources:
  - matrix.namespace.yaml
  - synapse.helmrelease.yaml
  - matrix-postgres.postgresql.yaml
  - synapse-smtp-config.secret.yaml
