---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: matrix-postgres
spec:
  enableLogicalBackup: false
  teamId: matrix
  volume:
    size: 20Gi
    storageClass: longhorn
  numberOfInstances: 3
  users:
    synapse: []
  databases:
    synapse: synapse
  postgresql:
    version: "15"
  patroni:
    initdb:
      lc-collate: C
      lc-ctype: C
      encoding: UTF8
