---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tmate

resources:
  - tmate-external.svc.yaml
  - tmate-keys.secret.yaml
  - tmate.namespace.yaml
  - tmate-server.deployment.yaml
  - tmate-server.svc.yaml
