---
apiVersion: v1
kind: Service
metadata:
  name: tmate-external
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: tmate
  type: LoadBalancer
