---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tmate-server
  labels:
    app: tmate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tmate
  template:
    metadata:
      labels:
        app: tmate
    spec:
      containers:
        - name: tmate-server
          image: tmate/tmate-ssh-server:latest
          env:
            - name: SSH_HOSTNAME
              value: "tmate.frickel.earth"
            - name: SSH_KEYS_PATH
              value: "/etc/tmate-keys"
            - name: HAS_WEBSOCKET
              value: "0"
            - name: USE_PROXY_PROTOCOL
              value: "0"
            - name: SSH_PORT_LISTEN
              value: "22"
            - name: SSH_PORT_ADVERTISE
              value: "22"
          securityContext:
            capabilities:
              add: ['SYS_ADMIN']
          volumeMounts:
            - mountPath: "/etc/tmate-keys"
              name: tmate-keys
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 25Mi
      volumes:
        - name: tmate-keys
          secret:
            secretName: tmate-keys
