---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres-operator
      version: '1.9.0'
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator
        namespace: flux-system
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
