---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      version: '1.1.1'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: flux-system
      interval: 1m
  values:
    groupName: dns.hetzner.cloud
    secretName:
      - hetzner-dns-private
