---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - cert-manager.namespace.yaml
  - cert-manager.helmrelease.yaml
  - cert-manager-webhook-hetzner.helmrelease.yaml
  - cloudflare-token.secret.yaml
  - acme-account-key.secret.yaml
  - hetzner-dns-private.secret.yaml
