---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - siewert-io.certificate.yaml
  - wildcard-k8s-prod-02-frickel-earth.certificate.yaml
  - wildcard-frickel-earth.certificate.yaml
