---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configMapGenerator:
  - name: prometheus-values
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - prometheus.values.yaml

resources:
  - ../../postgres/grafana-general-db1-prod.secret.yaml
  - grafana-azuread.secret.yaml
  - prometheus.helmrelease.yaml
