---
defaultRules:
  rules:
    etcd: false
    kubeProxy: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false

kubeProxy:
  enabled: false
kubeEtcd:
  enabled: true
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false

alertmanager:
  enabled: true
  config:
    inhibit_rules:
    - equal:
      - namespace
      source_matchers:
      - alertname = InfoInhibitor
      target_matchers:
      - severity = info
    receivers:
    - name: "null"
    route:
      routes:
      - matchers:
        - alertname = Watchdog
        receiver: "null"
        group_wait: 0s
        repeat_interval: 10m
      - matchers:
        - alertname = InfoInhibitor
        receiver: null
  podDisruptionBudget:
    enabled: true
  ingress:
    enabled: false

grafana:
  enabled: true
  defaultDashboardsTimezone: Europe/Berlin
  envValueFrom:
    GF_AUTH_AZUREAD_AUTH_URL:
      secretKeyRef:
        name: grafana-azuread
        key: auth-url
    GF_AUTH_AZUREAD_TOKEN_URL:
      secretKeyRef:
        name: grafana-azuread
        key: token-url
    GF_AUTH_AZUREAD_CLIENT_ID:
      secretKeyRef:
        name: grafana-azuread
        key: client-id
    GF_AUTH_AZUREAD_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-azuread
        key: client-secret
  grafana.ini:
    server:
      root_url: "https://grafana.frickel.earth"
    security:
      cookie_secure: true
    auth:
      disable_login_form: "true"
      oauth_auto_login: "true"
    auth.azuread:
      name: 'siewertIO Azure Auth'
      enabled: "true"
      allow_sign_up: "true"
      scopes: 'openid email profile'
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.frickel.earth
  plugins:
    - flant-statusmap-panel
    - grafana-piechart-panel
    - vonage-status-panel
  datasources:
    enabled: true
    defaultDatasourceEnabled: true
  serviceMonitor:
    enabled: true
  sidecar:
    dashboards:
      enabled: true
      folderAnnotation: 'internal.frickel.earth/grafana-folder'
      provider:
        disableDelete: true
        foldersFromFilesStructure: true
      searchNamespace: ALL

prometheus:
  enabled: true
  ingress:
    enabled: false
  prometheusSpec:
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    podMonitorNamespaceSelector:
      any: true
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      any: true
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      any: true
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
