apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.home.frickel.earth
  namespace: cert-manager
spec:
  secretName: wildcard.home.frickel.earth-prod
  issuerRef:
    name: letsencrypt-dns-hetzner-prod
    kind: ClusterIssuer
  commonName: 'home.frickel.earth'
  dnsNames:
  - 'home.frickel.earth'
  - '*.home.frickel.earth'
