---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix

resources:
  - matrix.namespace.yaml
  - ../postgres/synapse-general-db1-prod.secret.yaml
  - synapse-signingkey.secret.yaml
  - synapse.helmrelease.yaml
  - synapse-smtp-config.secret.yaml
