---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: matrix-postgres
spec:
  enableLogicalBackup: true
  teamId: matrix
  volume:
    size: 10Gi
    storageClass: hcloud-volumes
  numberOfInstances: 2
  users:
    synapse: []
  databases:
    synapse: synapse
  postgresql:
    version: "15"
  patroni:
    initdb:
      lc-collate: C
      lc-ctype: C
      encoding: UTF8
