apiVersion: v1
kind: Secret
metadata:
    name: synapse-smtp-config
    namespace: matrix
type: Opaque
stringData:
    smtp_config: ENC[AES256_GCM,data:kcDa9g/9QawwruVXnZ2PJNyhHRitW7DYcw0v/bU1yUun82Ux1AvURMWfqu07uT8rRY5BKP0pYORLWw20u56hOtKUA30spAS2Xy39PqwHNwQzPWLHmis03KlnTxDHKLJskHFB+k0zyT2x/KuAiRlIjuIubSv4Mifo3Myj9xnFSQzIQEkIrqHbPOoIJSL46Ko/EXYws0ZMODEOl7FRQtK1TYHhD8p/yDuexk8mRliNRbqHGvx9JK9d4C6Yae2+UwGsKA1PXJuUACRAaelRZB7nUW4gCMYsF60AbNo14Rvhhmoeho/IqZ9v,iv:Tl4IsSrkEkRwcRZktDwORlSDoTe3ZciFViyvHcnn0rs=,tag:OhOY4w91MnyrYWutpgMwNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vm9mww72aymqc4f85p7mc2hd850up8s8mgc9cyuz8hrpfee4p4uqdxjlwq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSGgvNjNlV1NMYU9lY2lQ
            UXA5bmxBUWRMVzBiQjI1S0Vad1JaWHcvbXg4CnZaSGtPYXZwM24wOUJvOXIzU2Ew
            QUhVcStLdWJmSiszZTFmYm1HYzRGd2sKLS0tIDJqaHpNRzVGMW1mdzVacDdYeStG
            bHN3di82cEs0aG12OHFUWkk2ckFUZ2MK9uBYxIsc8kF2VLGtRCSxGYdzyXoibSly
            MgSM0ycdRjirH1dFSlQfthus/cjOAoNf3+LxEnUZtI1UOAZDAlXnCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rsp46nn826senazrql2wxvecyskjujpaxkkap8ws4qa2sl9fdvjqmyn6qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V3NIeEhuYS9DN1h4L0N2
            dngyWEUwMTRYN3pGRGsyOXFPQWs3dnd1akNZCnhKMXFQUUl1MCtGV3lxKzY1ekY0
            OUN3dG5zYXdQWUx2c0hLb3lRV0kzSDQKLS0tIDIwNnRTemE1SGJIeUh2UnVycHNH
            UHJxbVdtL0F5RkRMeXRVOXJoMWlsWUkKchiZ8EXNrYi1WuQucDr4Nynd/nZnvlVn
            +mzuipfioG+1SpyZFNZRLa/J483NLsiyBtyIMI3ZPDZ08ITnUg4F3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T16:24:59Z"
    mac: ENC[AES256_GCM,data:EmhQFY7Pj4ppzWMRTjOMcpNaaRLzhD1r/7K9jA6HXfHs01gJNdlOiJOsEgeSig0+LVvyCSve0S6mKvSDPSza3bForxTUq3QOZ6bZyqn4reF6zxJYwFwJYRQMSNgubaEd0KVJkl3K5r74CCuQpEgXBZUgao0wctVMrontxx3ZsV8=,iv:p8frnNt7jWMNsRuq2+r0oQzvUCQCiiNWPg6AFkgsdEE=,tag:znq5Sm5yNf3i/ws2CZhPcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
