---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - metallb.helmrelease.yaml
  - metallb-system.namespace.yaml
  - egh-rr1.bgppeer.yaml
  - default.ipaddresspool.yaml
  - default.bgpadvertisement.yaml
