---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: '7.0.190'
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 10m
