---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configMapGenerator:
  - name: promtail-values
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - promtail.values.yaml

resources:
  - promtail.helmrelease.yaml
