---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siewert.io
  namespace: cert-manager
spec:
  secretName: siewert.io-prod
  issuerRef:
    name: letsencrypt-dns-cloudflare-prod
    kind: ClusterIssuer
  commonName: 'siewert.io'
  dnsNames:
   - siewert.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: matrix
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: matrix
