---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.k8s-prod-01.frickel.earth
  namespace: cert-manager
spec:
  secretName: wildcard.k8s-prod-01.frickel.earth-prod
  issuerRef:
    name: letsencrypt-dns-hetzner-prod
    kind: ClusterIssuer
  commonName: 'k8s-prod-01.frickel.earth'
  dnsNames:
    - 'k8s-prod-01.frickel.earth'
    - '*.k8s-prod-01.frickel.earth'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "asciinema,gitlab,matrix,monitoring,netbox,paperless,vault"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "asciinema,gitlab,matrix,monitoring,netbox,paperless,vault"
