---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden

resources:
  - vaultwarden.namespace.yaml
  - vaultwarden-policy.cnp.yaml
  - vaultwarden-secrets.secret.yaml
  - vaultwarden.statefulset.yaml
  - vaultwarden.ingress.yaml
  - vaultwarden.svc.yaml
