---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: internal-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - internal-pool
  communities:
  - 65501:12345
