---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - internal-advertisement.bgpadvertisement.yaml
  - internal-pool.ipaddresspool.yaml
  - metallb.helmrelease.yaml
  - metallb-system.namespace.yaml
  - router.bgppeer.yaml
