---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: metallb
      version: '0.13.11'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    speaker:
      frr:
        enabled: true
