---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  timeout: 20m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: metallb
      version: '0.13.7'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1m
  values:
    speaker:
      frr:
        enabled: true
    prometheus:
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        addressPoolExhausted:
          labels:
            severity: info
        bgpSessionDown:
          labels:
            severity: critical
