---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller
  namespace: unifi
  labels:
    app.kubernetes.io/name: unpoller
spec:
  namespaceSelector:
    matchNames:
      - unifi
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
