---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app.kubernetes.io/name: unpoller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
  podMetricsEndpoints:
    - port: 9130
      interval: 30s
      path: /metrics
