apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: unifi
type: Opaque
data:
    unifi-poller.conf: ENC[AES256_GCM,data:BbBVS2LiyQXbK9W+cUBk7TYw1YEfZrQXI64R+ZMt91O21VnQsuZPVjRfvoB5EeMsgglT1cdzpu89G0czacAQjThfrzpVzzxwoXb30VZUswa2MbnW/0r6H+h3MbHeQloAg0/IuZRYc9+zSn++/RMO0U0VZfc+SmKyBoea/n2J68LRQGQFloyCG7RSK5kqEZR7wIchrr+p5au89DKfgjasjbHPJDC6qY+ppljP3VC/KJdzRUTobrqgIEzqn/wV/rtaILQQIMqraejsM1u+eFFlus2oeaqozi5k23S2hXp/o7B0umhXalvC0F3IK1qnsV2hu+Y55n/O1uJH0ombBfX7mcZ0LIxaFdCjSinR9W8+hL1abfNcYNtJsR7clxPcrVwv7zoQjvEJ/Ub8wQl2WHIHK7+8djlNRqftMGBpvmCtehZny/QdhGkTeMsEv0dZU4uI+HoyFYw3hZxKmfZssFSFm9MMZXxndfuf2ysQeLOaihr7IK6EvzWkHutbdstMh84njtSOOJA9ELGIdcJ+ZatkI/OEDkRLtVzqxTlCdzANhL36Zj8H9moz+7KYe5MqJG2eMmWxSOBm7dyeULJCAtLytCok9OILsI5fdZ1KC4ItlntF+xSu3ANKefKYJ3pvC34QaUzJgLbzTZzdsoSqYy8d12mN1O/sYD7hpVkFnMMRR2nlvsn9Bs3SWf2r2UfNCsyMBDJam0jKabsdIDtpIHGVv1StxQLJ8ZAWco04lpteu9jNb2cNmvruaVLG2pdkMD/5bxMHhaUlmQ2GCZ/fk/plhQOHowHx/paWBNpcuze0+zsZCsS4pTrXiBi7x4JopUeJoeJ4bxsozBNYOw2TQjco9Vs1XTopKzrbuQ//sErd1emGaQwaCuqMW0SRdqkCh8fhosUi2rIJaCc=,iv:AEfRNdMYctjA7gsIcpwGOhaRzrFEgwMtAEAGNBdu5Jc=,tag:pfOYveTUJAOrX+FYRWbnmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vm9mww72aymqc4f85p7mc2hd850up8s8mgc9cyuz8hrpfee4p4uqdxjlwq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MTJ0bWkwRFRJczBMNzZO
            S3RpS3l0elBzcDBPZVc4ODRJRjhtaVA2L1RFCjVGeExMc1E4VGUxdXR1bEV6anFq
            Ni8wUXdVdjFRSUFzT0FOQkQ5cGFZVzQKLS0tIDN4S2FTaFM2aFRiZWtlZlVoSXVZ
            WFRRZVVYY253MHF2TGxMTEZrN2c4UVUK7KSdtmhqS0SqT0wDFTCwxNyaFt5drbGB
            jR3JAwcqpiq5Hw+0eaAb8HRYxXX72m+GrAErPF6aKPe4ePreZK2XMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19s84aypfuavsqjh3xhu9zwq4ku2e03m0ds0rsgrvh8zykskazq9sss0m0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdlhyMjlreTd2ZjFiU3Zo
            QkJTbVlhbUZiVGZjRW1HTEhLeG5rUFNrMkZnCnFUNHJWem1JV0FqUWU1N01XVWpY
            VTdaNVhiQkxpSVhoSWtsYVM5RnJWZmMKLS0tIGlmTXQyV0tGNzNKb0VscEIrc3lt
            eVBGREo0RitlbUJESC9NdlVidi9BSFkKBDn4nH7F/H1EJOr+Dn6Ao/Ew6k6zDKi+
            dpwyH8hci2jUPPdmiy5tZFw6qEatGieDvNbr8HVrKjTeS30/rt6WkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T00:22:13Z"
    mac: ENC[AES256_GCM,data:RuXhzLWJpKOUoXZmsIH1djtfIaG1XBgLiLse/5L7Cny/Ytbv+kHUQziqx8f/itlLIzELVepOpHAoWJzxq3uEvWeb2GOxIUeCkaUOWtCGZ/6BEWTHk5Q2h8FUvC7nRga218SWNf4ccbYhLzOrJHTd9TqqouEAdZ9hCIoJ4sGXrxY=,iv:jWhQNoMoI1DH2yBpKAGKwg8zNxmaGsY4O8GIWdQPY2U=,tag:tsSMaa6etdHb2GnfslpuBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
