---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: unifi
  labels:
    app.kubernetes.io/name: unpoller
spec:
  selector:
    app.kubernetes.io/name: unpoller
  ports:
    - name: metrics
      port: 9130
