apiVersion: v1
kind: Secret
metadata:
    name: grafana-azuread
    namespace: monitoring
type: Opaque
stringData:
    auth-url: ENC[AES256_GCM,data:tgMLwVVACe7iosW8v1H6QGJhRcmfmPid40bpeanmrHp2/brWEMoDeD2ChWZfCmH8rg0KEgmImrBBHxpljclLAQMmEZ2gJTtMoNeFRp5T64QUH60mIlx38bQ8SUM=,iv:Ds8QsHcN5Fll8P59nrlT9PAv0cIAYT5a8Rs9VwWC76U=,tag:8cQOLG5y2AYPp+GzemnD5g==,type:str]
    token-url: ENC[AES256_GCM,data:8l9Dz/AUx266E1bxIfr14ab0g9ZzSsVEvmPeiqsckQhjuGxLbL4HoRK/6SNf2RG6TVOIEs2fO4lE0X+6qBbALe2RXBjWswmDGfPYHBRQ3yWaYYIFb+/DCA==,iv:o9+rt5oCx1Tdit+ulhXQBezW0f+9Dfp9MijiQX9Rxp8=,tag:GcL+0wQTY8/kn5nw8//2rQ==,type:str]
    client-id: ENC[AES256_GCM,data:rJ5umQp+cmuxF7IHeFH/yxERqT0TsNp5xvxAhtbkx41sxU9p,iv:42hWiz0ofapGojhUtZoSckLh+fbiRWgm4cMllnk9/ZA=,tag:Z4Q7xS50jgJZ4ES6yWLSqQ==,type:str]
    client-secret: ENC[AES256_GCM,data:1m27WjSlH3ynCsV6EkNm/g7/hgDu20Ec8nxxRPq94edkgyfKL08CzA==,iv:YjjVm0/1Fztzfir0L3rx0M3XbTI1bZedaiOfzXocibs=,tag:KAjrGlGQ7owsPkwL6YFPAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vm9mww72aymqc4f85p7mc2hd850up8s8mgc9cyuz8hrpfee4p4uqdxjlwq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Ui9icE1FM25WQjVDbXVr
            T3dsdzFYZUtjU29vT0Q3eHF2V1FSTk5NSVNrCm1BbWk4Mzg0czdMcGlPd2NWMFpl
            czBHMkVaaGU0Ujg3cWZTWXYwY2p1NzgKLS0tIFo4SUpSWVQ3M2NxeWlvNUkycU9I
            WGIyMWVaMDVZb0t1Qm52a1VWMDdpWVEKngrdDFrXahevLYqV4VkHLhj3k5T+kKam
            KrfInLyy5/EoPMhgnGPhar4d987ml9qL3+Uh+6hQ8CUfhTzXjX7doA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ythvxddew4xy5wyzs90zdjsrzlhrswnhlhv0dqk9lt3sywxfm9cqzld7g4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNGFzR0gxUFQvRzBqeVd5
            VS81QktHeGk2d3hkVzFNVWpFa0ptVzdoSzFjCldNaXpVb3kwTU9kS3lOVUdueHRn
            Mm9yZVZhM1BoRllIWFROZEZxOTQ4K1UKLS0tIDQvRk5jV1hWbFJrYTBuaHd6Z1RH
            dFpKazdsTFB3aHRFVDNXRDFZcUw3UjAKBkQ6PS+7QA8J+xxrxCRq3qNzAIIEpvKi
            5piwZDRl5zGGuJ0UfOGfPlEtmmhKlM1RtYV2lVjEeHe+f8mmmZev0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T21:05:43Z"
    mac: ENC[AES256_GCM,data:+s1rz9cQf9IMkL3avTtBZ3meSuSkq9oJ908JC4DAWT4ocTBTfWKSFuOarWizWXGHoFBH0QCi0UoUP+WhRDM3RMX5LA/NBs2eA1f2GOcHc6r//MA6j1mGmuL85iZ+HM81mulxNHMNL1RLUrjjUx8Xe2BqioDb9HBKOGwmMmU5KZk=,iv:5upSXd8ztujRED2NOGUGgvW31E/+F+UHcKJuRYvMmWo=,tag:oE0+B0/gNc3oUgbaQuivEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
