---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      version: 3.1.2
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    credentials:
      existingSecret: cloud-credentials
    snapshotsEnabled: false
    deployNodeAgent: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: burning-data
        prefix: k8s-prod-01
        config:
          region: nl-ams
          s3Url: https://s3.nl-ams.scw.cloud
