apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: cert-manager
spec:
  certificates:
  - secretName: wildcard.k8s-home.frickel.earth-prod
  defaultCertificate:
    secretName: wildcard.k8s-home.frickel.earth-prod
