apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: cert-manager
spec:
  certificates:
  - secretName: wildcard.home.frickel.earth-prod
  defaultCertificate:
    secretName: wildcard.home.frickel.earth-prod
