apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: backup-matrix
  namespace: velero
spec:
  schedule: '@every 1h'
  template:
    excludedResources:
    - replicasets.apps
    - jobs.batch
    hooks: {}
    includedNamespaces:
    - matrix
    metadata: {}
    ttl: 48h0m0s
  useOwnerReferencesInBackup: false
status: {}

