apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: backup-kube-system
  namespace: velero
spec:
  schedule: '@every 3h'
  template:
    excludedResources:
    - replicasets.apps
    hooks: {}
    includedNamespaces:
    - kube-system
    metadata: {}
    ttl: 48h0m0s
  useOwnerReferencesInBackup: false
status: {}

