apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: backup-asciinema
  namespace: velero
spec:
  schedule: '@every 24h'
  template:
    excludedResources:
    - replicasets.apps
    hooks: {}
    includedNamespaces:
    - asciinema
    metadata: {}
    ttl: 48h0m0s
  useOwnerReferencesInBackup: false
status: {}

