---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomizations
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-prod-02/kustomizations
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: clusters
