---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - cert-manager.namespace.yaml
  - cert-manager.helmrelease.yaml
  - cert-manager-webhook-hetzner.helmrelease.yaml
  - hetzner-dns-private.secret.yaml
  - letsencrypt-dns-hetzner-prod.clusterissuer.yaml
  - letsencrypt-prod.clusterissuer.yaml
