---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-prod-01/longhorn-system
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: clusters
