---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./base/kube-system/reflector
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: clusters
