---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-operator
      version: '0.11.2'
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
      interval: 1m
