---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: general-db1-prod
spec:
  enableLogicalBackup: false
  teamId: general
  volume:
    size: 20Gi
    storageClass: hcloud-volumes
  numberOfInstances: 2
  users:
    synapse: []
    paperless: []
    grafana: []
    vaultwarden.vaultwarden: []
  databases:
    synapse: synapse
    paperless: paperless
    grafana: grafana
    vaultwarden: vaultwarden.vaultwarden
  postgresql:
    version: "15"
  patroni:
    initdb:
      lc-collate: C
      lc-ctype: C
      encoding: UTF8
