---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres

resources:
  - postgres.namespace.yaml
  - synapse-general-db1-prod.secret.yaml
  - paperless-general-db1-prod.secret.yaml
  - grafana-general-db1-prod.secret.yaml
  - general-db1-prod.postgresql.yaml
