---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-paperless
  labels:
    team: acid
spec:
  enableLogicalBackup: false
  teamId: acid
  volume:
    size: 8Gi
  numberOfInstances: 2
  users:
    paperless: []
  databases:
    paperless: paperless
  postgresql:
    version: "15"
