---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
  - paperless.namespace.yaml
  - paperless-redis.helmrelease.yaml
  - ../postgres/paperless-general-db1-prod.secret.yaml
  - paperless.secret.yaml
  - paperless.statefulset.yaml
  - paperless.ingress.yaml
  - paperless.svc.yaml
