---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paperless
  labels:
    kubernetes.io/app: paperless
spec:
  selector:
    matchLabels:
      app: paperless
  serviceName: "paperless"
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - image: ghcr.io/paperless-ngx/paperless-ngx:1.13.0
          name: paperless
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "4Gi"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          env:
            - name: PAPERLESS_REDIS
              value: "redis://paperless-redis-master:6379"
            - name: PAPERLESS_DBHOST
              value: "general-db1-prod.postgres"
            - name: PAPERLESS_DBUSER
              value: "paperless"
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless.general-db1-prod.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Berlin"
            - name: PAPERLESS_OCR_LANGUAGES
              value: "eng deu"
            - name: PAPERLESS_OCR_LANGUAGE
              value: "deu"
            - name: PAPERLESS_URL
              value: "https://paperless.frickel.earth"
            - name: PAPERLESS_ALLOWED_HOSTS
              value: "*"
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless
                  key: secret_key
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: consume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: media
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 20Gi
