---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: github-auth
  url: ssh://git@github.com/tomsiewert/kubernetes
