---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: longhorn
      version: '1.5.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.home.frickel.earth
