---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: ingress-nginx
      version: '4.4.2' # stuck here because of k3os v1.21
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    service:
      externalTrafficPolicy: Local
    controller:
      service:
        ipFamilyPolicy: "RequireDualStack"
        ipFamilies:
          - IPv4
          - IPv6
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
